### ISSUE TITLE
load gists data into modern Elasticsearch on cloud VM server

### ISSUE THREAD

**Issue by micahstubbs** [enjalot/blockbuilder-search-index#55]
load gists data into modern Elasticsearch.  today, modern Elasticsearch ===  version`6.3.2` https://www.elastic.co/downloads/elasticsearch-oss

do this locally first an as exercise. 
 
- [x] load gists data into modern Elasticsearch on my local machine
 
when all goes well locally

- [x] deploy blockbuilder-graph-search-index + Elasticsearch  to a cloud VM server

### stretch goal 
- [ ] package blockbuilder-graph-search-index + Elasticsearch up as a docker container 

### collaboration checklist

- [x] get @enjalot's local blockbuilder search dev environment up and running 
- [x] review PRs, test code locally
- [x]  rinse and repeat
- [x] stand up some servers
- [x] deploy new backends: Elasticsearch 6.4.0 and index d3 gist data on servers
- [x] test with local search frontend and new search backend https://github.com/enjalot/blockbuilder-search-index/issues/55#issuecomment-416453870
- [x] deploy indexing server with systemd
- [x] setup cronjobs for continuous indexing
- [x] setup elasticsearch with systemd
- [x] deploy free commercial Elasticsearch 6.4.0 to enable ~security~ monitoring features https://github.com/enjalot/blockbuilder-search-index/issues/55#issuecomment-417414093
- [ ] whitelist IP addresses for servers - firewall rules
- [ ] fix module parsing bug https://github.com/enjalot/blockbuilder-search-index/issues/56
- [ ] test it all
- [ ] update blockbuilder config to point to new servers
- [ ] deploy new blockbuilder & blockbuilder-search code to existing blockbuilder server

**Comment by micahstubbs** [comment]
reading about hardware requirements for elasticsearch https://www.elastic.co/guide/en/elasticsearch/guide/current/hardware.html

**Comment by micahstubbs** [comment]
the low end of those recommendations would be an instance like this on gcp 
![Uploading Screen Shot 2018-08-24 at 6.49.52 AM.png…]()

**Comment by micahstubbs** [comment]
ok, I succeeded in loading 29,422 users into my local Elasticsearch v6.3.2 instance

![screen shot 2018-08-25 at 9 59 19 am](https://user-images.githubusercontent.com/2119400/44620683-9de85f80-a84d-11e8-8066-ae7b75b08296.png)

**Comment by micahstubbs** [comment]
one option for provisioning cloud elasticsearch instances / cluster nodes https://bitnami.com/stack/elasticsearch

**Comment by micahstubbs** [comment]
deep in this now.  improving the regex that we use to detect d3 modules

```javascript
/(d3-[\w-]*)(?=\.)/
```

https://regexr.com/

![screen shot 2018-08-26 at 1 13 09 am](https://user-images.githubusercontent.com/2119400/44626192-3f62c600-a8cd-11e8-9965-b81920f24540.png)

**Comment by micahstubbs** [comment]
another option for deployment https://console.cloud.google.com/marketplace/details/click-to-deploy-images/elasticsearch?q=elasticessearch&id=86b2dc84-fe5e-434c-802e-3f524eddb6d9&project=blockbuilder-search

![screen shot 2018-08-26 at 9 51 33 pm](https://user-images.githubusercontent.com/2119400/44641112-3b40b200-a97a-11e8-9d59-a6e1bd58ef50.png)

**Comment by micahstubbs** [comment]
🎉  found the answer

```yml
transport.host: localhost
network.host: 0.0.0.0
```

![screen shot 2018-08-27 at 10 14 42 pm](https://user-images.githubusercontent.com/2119400/44702126-ae175f00-aa46-11e8-8f30-0e40801bae9b.png)
https://github.com/elastic/elasticsearch/issues/19987#issuecomment-298597068

**Comment by enjalot** [comment]
added 

[http.cors.enabled: true](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html)
 to elasticsearch.yaml 
so dejavu can work from localhost and hit the hosted index. Not sure how to restart elasticsearch

**Comment by enjalot** [comment]
we should look into doing this for securing the index
https://www.elastic.co/guide/en/elastic-stack-overview/current/get-started-enable-security.html

**Comment by enjalot** [comment]
ok, blockbuilder and blockbuilder-search code is poised for deployment. Once we do a bit more testing  and secure the index we can point the blockbuilder config at the new elasticsearch backend and deploy the code in just a couple minutes!

**Comment by micahstubbs** [comment]
> Not sure how to restart elasticsearch

here's how I like to do it 😄 
es === elasticsearch

```bash
ssh bb-search
# attach tmux session that elasticsearch is running in
tmux a -t es
# verify that you are in the es directory
# elasticsearch-6.4.0
# stop es process
ctrl + c
# start elasticsearch again
bin/elasticsearch
# exit tmux
ctrl + b d
```

**Comment by micahstubbs** [comment]
good call, logged https://github.com/enjalot/blockbuilder-search-index/issues/59 to enable security for the elasticsearch instance

**Comment by micahstubbs** [comment]
> ok, blockbuilder and blockbuilder-search code is poised for deployment. Once we do a bit more testing and secure the index we can point the blockbuilder config at the new elasticsearch backend and deploy the code in just a couple minutes!

awesome - let's try to do this later today T 8/28, PDT early evening

**Comment by enjalot** [comment]
I've fixed it so you can now `sudo systemctl start elasticsearch` (or stop). See README of deploy folder for more info.
this is more stable than leaving a tmux window open ⭐️

**Comment by micahstubbs** [comment]
```bash
ssh bb-search
cp -r elasticsearch-6.4.0-apache-2/config elasticsearch-6.4.0/
cp -r elasticsearch-6.4.0-apache-2/data  elasticsearch-6.4.0/
```

**Comment by micahstubbs** [comment]
```bash
/etc/systemd/system/elasticsearch.service
```
![screen shot 2018-08-30 at 11 08 40 am](https://user-images.githubusercontent.com/2119400/44870423-1338a380-ac45-11e8-8495-69795adc03fa.png)

shows me this:

```bash
[Unit]
Description=Elasticsearch

[Service]
ExecStart=/home/ubuntu/elasticsearch-6.4.0/bin/elasticsearch
Restart=always
RestartSec=10                       # Restart service after 10 seconds if node service crashes
StandardOutput=syslog               # Output to syslog
StandardError=syslog                # Output to syslog
SyslogIdentifier=elasticsearch-server
User=ubuntu
#Group=<alternate group>
Environment=DISPLAY=:99


[Install]
WantedBy=multi-user.target
```

**Comment by micahstubbs** [comment]
since I gave the new free commercial elasticsearch the same `elasticsearch-6.4.0` directory name, the service should work as is.  it should serve the new free commercial version as soon as I restart the service with:

```
sudo systemctl stop elasticsearch
sudo systemctl start elasticsearch
```

**Comment by micahstubbs** [comment]
ok, Elasticsearch is back up and working 🎉 

![screen shot 2018-08-30 at 11 14 09 am](https://user-images.githubusercontent.com/2119400/44870744-d7520e00-ac45-11e8-8161-bbcdc60259c9.png)

![screen shot 2018-08-30 at 11 12 07 am](https://user-images.githubusercontent.com/2119400/44870723-cb664c00-ac45-11e8-971b-df040e2b94a4.png)
